# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' Multiply a number two times.
#'
#' @param x A single integer.
#' @return a integer.
#' @export
timesTwo <- function(x) {
    .Call('_testnewnew_timesTwo', PACKAGE = 'testnewnew', x)
}

